"""Description of changes

Revision ID: f38dbfe49a77
Revises: 9d63e60f9d47
Create Date: 2024-12-07 10:30:38.502817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f38dbfe49a77'
down_revision = '9d63e60f9d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('exported_at')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('documents_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'enrollees', ['enrollee_id'], ['id'])

    with op.batch_alter_table('enrollees', schema=None) as batch_op:
        batch_op.drop_constraint('enrollees_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'FINANCE', 'STAFF'),
               nullable=True)
        batch_op.drop_index('email')
        batch_op.create_index(batch_op.f('ix_staff_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_email'))
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'FINANCE', 'STAFF'),
               nullable=False)

    with op.batch_alter_table('enrollees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('enrollees_ibfk_1', 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('documents_ibfk_1', 'enrollees', ['enrollee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exported_at', mysql.TIMESTAMP(), nullable=True))

    op.create_table('password_reset_tokens',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('expires_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
